import type { Metadata } from "next";
import { Geist, Geist_Mono, Inria_Sans } from "next/font/google";

import "./globals.css";
import Navbar from "./component/navbar";
import Sidebar from "./component/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inriaSans = Inria_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"], 
  variable: "--font-inria-sans", 
});
export const metadata: Metadata = {
  title: "FastProforma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inriaSans.variable} antialiased`}
      >
        <div className="fixed flex justify-between w-full">
          <Sidebar />
          <Navbar />
        </div>
        <div className="pl-[275px] pt-16 text-balance">{children}</div>
      </body>
    </html>
  );
}
